### ISSUE TITLE
Data2xml 0.8.0 breaks route53

### ISSUE THREAD

**Issue by markcallen** [chilts/awssum#125]
Trying any post to route53 (ChangeResourceRecordSets) returns a 400 error every time.

The data2xml call is returning [Function], not the xml string.

I have downgraded data2xml to 0.4.0 in my package.json which fixes the issue.  Not sure if it breaks other things in awssum as I only use it for route53.

**Comment by chilts** [comment]
Hiya Mark,

Really sorry about that. I've fixed this in c6444dfe.

I've also fixed it in the v0.12 branch and pushed a new v0.12.1 tag to GitHub and a bugfix release to NPM.

The fix is to set data2xml to be v0.4.x as you did, however the longer term fix is to change my code to use the new way data2xml allows people to set config. I'll open a new issue for this.

Thanks for reporting.

Cheers,
Andy
