### ISSUE TITLE
Very Poor Document

### ISSUE THREAD

**Issue by hrf-henry** [chilts/awssum#141]
I tried to use your API, seem cover a lot of things. However once I got problem, I found no document to understand/fix my issue. I have to remove this and using aws-sdk instead of.

Very poor documentation, sorry to saying this

**Comment by techtribe** [comment]
If you could share your issue, you can help us understand what we are missing. I am not saying we are full-featured, but lets just say that AWS APIs are huge and a lot...so our work of documenting is never done, especially because not all AWS documentation is complete.

It would help also if you name what you are missing, so we could ensure that in the (near) future that will not happen anymore.

And btw, use the aws-sdk, it is a good setup but not all endpoints/services/options are supported (yet).

**Comment by chilts** [comment]
Thanks for closing Joey.

Shame that whoever it was couldn't find time to help, though they could find time to complain.

Cheers,
Andy

**Comment by techtribe** [comment]
Had the same idea. Too easy to just shout about something bad without your problem or suggestion.

#keepingthepositivevibe ;)

Hy

Verzonden vanaf mijn Samsung Galaxy NoteAndrew Chilton notifications@github.com schreef:Thanks for closing Joey.

Shame that whoever it was couldn't find time to help, though they could find time to complain.

Cheers,
Andy
