### ISSUE TITLE
Node v.0.10? + defaults rejectUnauthorized to true

### ISSUE THREAD

**Issue by gconaty** [chilts/awssum#162]
See here as an example: http://shlomoswidler.com/2009/08/amazon-s3-gotcha-using-virtual-host.html

Basically the SSL cert validation fails.  So passing in a BucketName like 'my.host' will resolve to my.host.s3.amazonaws.com  and fail validation.

Is it possible to skip the BucketName and put the whole location in the Path?

**Comment by chilts** [comment]
Hi Garrett,

Ah interesting. I just did a quick try by switching the bucket name to the path rather than the host, but it didn't work so I'll look into it further later on.

Thanks for raising this issue.

Note: You should start using awssum-amazon-s3 with the new plugin architecture. The old AwsSum v0.12 and earlier are now deprecated.

Cheers,
Andy

**Comment by chilts** [comment]
AwsSum is now deprecated in favour of the offical aws-sdk from Amazon. Thanks for opening this originally.
