### ISSUE TITLE
S3 Region Required

### ISSUE THREAD

**Issue by greatwitenorth** [chilts/awssum#17]
A region is required when creating a s3Service object, yet it stated on:
http://docs.amazonwebservices.com/general/latest/gr/rande.html#s3_region
that if you bucket is in US Standard, no region is required therefore it must be left blank (which is not allowed).

**Comment by chilts** [comment]
For US standard, use the 'us-east-1' region.

I'm afraid that due to the way S3 is implemented at Amazon, it is horribly inconsistent and my library is to help smooth over the consistencies, hence I require a region so that they all look the same to you. :)

Whilst they say it's optional, I still use the region in the bucket URL so that again my code is smaller and more consistent, instead of having ifs and elses for buckets which seemingly have no region. :)

Closing since I'll keep the code as it is. Thanks for raising the question.

**Comment by ricick** [comment]
What if I want to use this library to list all buckets across all regions?

**Comment by chilts** [comment]
You'll have to create as many instances of S3 as there are regions, each with the relevant region passed into the constructor, then list each of these separately. There is no single operation in any of the Amazon Web Services which queries across regions, therefore this is reflected in how this API is put together.

All Amazon Web Services are region specific and even in the case of ones where there is only one region (e.g. SES), it is still tied to us-east-1. Regions in AWS are a fundamental concept, therefore to do what you want, you'll have to write a small bit of custom code to do it for you.

**Comment by ricick** [comment]
ok cheers

**Comment by ricick** [comment]
It seems that s3.ListBuckets returns all buckets across all regions, regardless of what region you pass to the s3 instance then you create it.
