### ISSUE TITLE
Support for http/https agent is needed

### ISSUE THREAD

**Issue by frooble** [chilts/awssum#18]
In awssum.js simply adding 'agent: options.agent' to reqOptions object in AwsSum.prototype.request will allow for insertion of an agent object and allow for use of proxy and such

``` javascript
AwsSum.prototype.request = function(options, callback) {
    var self = this;

    // check here that we have everything

    // since this can be called on both close and end, just do it once
    callback = _.once(callback);

    var reqOptions = {
        method  : options.method,
        host    : options.host,
        path    : options.path,
        headers : options.headers,
        port    : options.port, // to make testing easier
        agent   : options.agent // to enable proxy utilization
    };
```

The addExtras mechanism can be used to add the agent

``` javascript
s3.addExtras = function(options, args) {
    options.agent = myAgent;
};
```

**Comment by chilts** [comment]
Sounds like a good idea. In the next version of AwsSum there is the ability to set to the http agent as well as the https agent, but I like your idea of being able to override it.

Of course, since it'll be dependent on your local configuration, then the best place for it will be on the object itself.

e.g.

s3.userAgent(myUserAgent);

Putting it in either the call or in the code (in your addExtras) function won't make sense since that is service dependent, not environment dependent. Hope that makes sense. :)

I'll add this to the next version of AwsSum.

**Comment by frooble** [comment]
The agent i was talking about was the http.agent as in
http://nodejs.org/api/http.html#http_class_http_agent

The  user agent string (e.g. "Mozilla/5.0 (Windows; U; Windows NT 5.1;
en-US) AppleWebKit/525.13 (KHTML, like Gecko)
Chrome/0.2.149.27Safari/525.13") I don't believe is really used by the
aws services. But
overriding it is something that would/could be supported by the http.agent
mechanism. The specific agent implementation i am using is _tunnel_ (
https://github.com/koichik/node-tunnel) which does support User-Agent
string overrides.

Thanks,
Mike

On Wed, May 9, 2012 at 3:35 PM, Andrew Chilton <
reply@reply.github.com

**Comment by chilts** [comment]
Hiya,

I've finally added the ability to define your own agent. Please let me know if this is fine for what you need.

I do apologise for taking this long, I didn't originally understand your request when I look back on it now. :)

Example here:
- https://github.com/appsattic/node-awssum/blob/master/test/integration/agent.js

Cheers,
Andy
