### ISSUE TITLE
Add additional encodings to results expected from AWS

### ISSUE THREAD

**Issue by frooble** [chilts/awssum#22]
Currently, requests are performed with the expectation that all content returned is 'utf8', however for some services, especially s3, s3 the content may be returned with some other encoding (in the case of s3 it is however the content was uploaded)

``` javascript
AwsSum.prototype.request = function(options, callback) {
    var self = this;

  /* ........ removed content ..............*/

    // do the request
    var req = https.request( reqOptions, function(res) {
        // do everything in utf8 (and therefore the 'data' event emits a UTF8 string)
        res.setEncoding('utf8');
        res.body = '';

        // when we get some data back, store it
        res.on('data', function(chunk) {
            res.body += chunk;
        });
```

**Suggest that the code be modified to support additional encodings in the response from AWS**

**Comment by chilts** [comment]
Hi frooble,

It looks like you're using an older version of AwsSum since UTF8 is no longer the default. Can you upgrade to v0.5.1 (or get the master branch from GitHub) and make sure it does what you want it to.

I'll close this issue but feel free to raise a new one if it still doesn't do what you need. :)

Many thanks,
Andy
