### ISSUE TITLE
API suggestion: Remove awsAccountId from constructors

### ISSUE THREAD

**Issue by 5mk** [chilts/awssum#4]
I'm not sure if this is the right place to put suggestions of this kind, reject it if I'm wrong. There's an `awsAccountId` parameter in each constructor in `lib/amazon`. This parameter is superfluous and is almost never needed for working with AWS. In those rare cases when it is required it can be fetched with one request from Amazon. So my suggestion would be to take it away to simplify API.

**Comment by chilts** [comment]
Hi nab,

Thanks for your suggestion. Can you tell me which request to Amazon can get the AccountId? I'm not aware of that at the moment so it could help.

You're right, it's not used much - from what I can see it's only sometimes in S3 and not used in any other service.

Cheers,
Andy

P.S. I'd also like to change the constructors slightly anyway, so may put this in for the next release. :)

**Comment by 5mk** [comment]
AWS Account ID is there in almost any response for queries to EC2 like DescribeInstances, DescribeImages etc in a tag `ownerID` in XML response. I would pick [DescribeSecurityGroups](http://docs.amazonwebservices.com/AWSEC2/latest/APIReference/ApiReference-query-DescribeSecurityGroups.html) as there's always a default security group which holds AWS account ID.

Kind Regards,
Nikita

**Comment by chilts** [comment]
What I'll do is make the AwsAccountId required in the cases where the operation needs it and pass it to the user of the library to provide it, either by doing DescribeSecurityGroups themselves or by providing it from their credentials page when they are logged in to http://aws.amazon.com/

By making AwsSum do it for the user makes the code way more complicated and it's something that is both easily found and static, so I'll just change the operations that require it to make sure it is passed in.

Thanks for your help and I'll ping you at the next major release (can't say I know when that'll happen but it should be soonish).

Cheers,
Andy

**Comment by chilts** [comment]
Since the AwsAccountId is static, I don't think fetching it from DescribeSecurityGroups or anything like that makes a lot of sense but instead just adds a lot of code.  Also, EC2 has it in responses, but S3 requires in in others ... it's a bit mix'n'match with no rhyme or reason. It's easy enough to add along with the key and secret so I'm going to close this issue as wont fix.

Many thanks for the suggestion though. :)

**Comment by caoilte** [comment]
I found the requirement for this constructor parameter confusing for the same reason that the initial poster did.

**Comment by chilts** [comment]
Hey Guys,

I waivered and figured the audience knows best. Actually, I re-arranged so that the constructors take an opts (object) rather than ordered args so it was a good time to make it optional.

It is still _required_ in Amazon Simple Queue Service (SQS).

Will be in v0.5.0 when I release in a few days time. :)

Cheers for keeping on at me.
Andy
