### ISSUE TITLE
Support for GreenQloud's truly green cloud

### ISSUE THREAD

**Issue by sputnick** [chilts/awssum#46]
Hey Andy,

it would be awesome to have support for GreenQloud's Compute Qloud and Storage Qloud API's that are Amazon EC2 and S3 compatible. See http://greenqloud.com

Compute Qloud (CQ):
Endpoint: api.greenqloud.com
Region: is-1 (GreenQloud.ICELAND)
Availability-zone: is-1a
Supported commands: 
http://support.greenqloud.com/entries/20182286-supported-commands-for-the-compute-api

Storage Qloud (SQ):
Endpoint: s.greenqloud.com
Region: is-1 (GreenQloud.ICELAND)

Thanks
Eirikur Hrafnsson
Co-Founder GreenQloud

**Comment by chilts** [comment]
Hi Eirikur,

Many thanks for raising this issue and thanks for helping me get started on GreenQloud.

I have some code on my machine now but not checking it in at the moment. I have a couple of integration tests for both EC2 and S3 which just call a couple of operations which don't have side-effects, but in one of my cases the test comes up with a different error than EC2. I'm looking into this now.

This is just a status update since I have to go and do some other stuff, but it's on it's way. :) I'll post my error later once I've understood it a bit and made sure my code is ok. Expect to see an update in the next day or so.

Cheers,
Andt

**Comment by chilts** [comment]
Hi Eirikur,

Would you like to check out master and have a play with it.

Please note that a number of the integration tests didn't work the same as the Amazon equivalents, so I have (for the moment) deleted them from the code. Have a look at the difference between:
- test/integration/amazon-ec2.js
- test/integration/greenqloud-ec2.js

And:
- test/integration/amazon-s3.js
- test/integration/greenqloud-s3.js

Also see the examples/greenqloud/ folder for some examples on using it.

Cheers,
Andy

**Comment by sputnick** [comment]
Excellent! We will test thoroughly as we have already started building our new management console based on awssum and meteor :D

Thanks again for creating such a great library.

cheers
Eiki
