### ISSUE TITLE
SQS: How to SendMessage without access key ID & secret access key?

### ISSUE THREAD

**Issue by michael-lawrence** [chilts/awssum#48]
I currently have a message queue that allows anyone to send a message to it, regardless if they have an AWS account or not. However, I cannot send a message to this queue using node-awssum unless I provide the access key ID & secret access key. I've tested that it works without supplying those values by manually creating an http client, but I'd rather use your library. How can I achieve this? Here's my code:

```
var awssum = require('awssum');
var amazon = awssum.load('amazon/amazon');
var Sqs = awssum.load('amazon/sqs').Sqs;

try {
    var sqs = new Sqs({
        'awsAccountId' : 'xxxxxxxxxxx',
        'region' : amazon.US_EAST_1
    });

    var optionsMyQueue = {
        QueueName : 'xxxxxxx',
        MessageBody : 'HelloWorld',
    };

    sqs.SendMessage(optionsMyQueue, function(err, data) {
        console.log('Sending a message to a queue');
        if(err) console.log('err: ' + err);
        if(data) console.log('data: ' + JSON.stringify(data));
    });
} catch(ex) {
    console.log('Error: ' + ex);
}
```

**Comment by chilts** [comment]
Hi Michael,

Oh wow. Ok. :) Didn't know that you could do that (though I guess a similar thing is signed requests in S3 to allow other people to download files).

Hmm ... let me think. It's quite fundamental I guess so let's see what we can work out.

Firstly, can you point me to the docs where this is described so I can learn a bit more? Also, I presuming that if you can give AwsSum the wrong awsAccountId and no secretKey, then the signature generated (which would be invalid) is ignored at the AWS endpoint? :)

Hope you don't mind me asking some questions just so I can get some more context of what is required. I have an idea, but it is not yet fully-formed. :)

Cheers,
Andy

**Comment by chilts** [comment]
20:28:09 @chilts so I've never heard of being able to whack something on a queue without needing credentials
20:28:44 < pandemic> yeah, you can add a wildcard to allow anyone to send messages
20:28:57 < pandemic> the other AWS libs for node don't allow it either for some reason
20:29:10 @chilts if you put 'xxx' and 'yyy' in for access key and secret, does it work?
20:29:12 < pandemic> but when I tried just using the http client and didn't pass the credentials it works
20:29:13 @chilts ie. some made up values?
20:29:14 < pandemic> nope
20:29:21 < pandemic> because it tries to validate them
20:29:21 @chilts ok, so it _does_ check the signature
20:29:23 @chilts righto
20:29:27 @chilts that's good to know
20:29:49 @chilts are there any other operations you can do on a queue (or in SQS) without credentials?
20:29:50 < pandemic> yeah, if you just leave out anything related to a signature it should work
20:29:53 @chilts or just PutMessage
20:29:56 < pandemic> i think all of them
20:30:01 @chilts oh really
20:30:11 < pandemic> however, I tried this on SNS and you MUST supply the signature
20:30:20 < pandemic> SQS is different for some reason
20:30:26 @chilts interesting
20:30:53 @chilts I think now that I've implemented all the services, it'll be lots of outlier fixes which aren't apparent from the docs :)
20:31:05 @chilts but it's great, since it'll make the library more bullet-proof

20:31:18 < pandemic> nice :)
20:31:26 @chilts ok, so I think we might need to make a client which has the same operations but for which it doesn't perform any signature
20:31:31 @chilts shouldn't be too hard
20:31:43 < pandemic> yeah, i think it should just be pulling out a few calls right?
20:31:45 @chilts mind if I paste this conversation into the GitHub issue?
20:31:50 < pandemic> sure thing
20:32:05 @chilts calls, as in operations for SQS, or internal calls to the signature code?
20:32:19 < pandemic> internal calls, like trying to generate a hash, etc
20:32:34 @chilts yeah, that bit is pretty easy since the top-level object (awssum) doesn't do much for you
20:32:42 @chilts just some defaults (like GET, expect 200, etc)
20:32:49 @chilts so the API will be :
20:33:29 @chilts var sqs = awssum.load('amazon/sqs');
20:33:35 @chilts var sqsSigned = sqs.Sqs;
20:33:42 @chilts var sqsUnsigned = sqs.SqsUnsigned;
20:33:46 @chilts or something along those lines
20:33:49 @chilts how does that sound?
20:33:58 @chilts ie. the .Sqs is the same as it currently is
20:34:15 @chilts the .SqsUnsigned is the new one without having to provide keys, or generate signatures
20:34:20 < pandemic> hmm, couldn't you just make it check to see if the key and secret key are passed, and if they don't exist then generate an unsigned version?
20:34:32 @chilts hmm, let me think
20:34:44 < pandemic> lemme look at your code, brb
20:34:49 @chilts I'd have to make it optional in all services since that checking is done in the Amazon base-class
20:34:54 @chilts but I _could_ do that
20:35:11 < pandemic> yeah, it seems like that would make sense just in case AWS changes something on their end
20:35:15 @chilts it may mean that people create object and it doesn't work since they didn't supply keys
20:35:30 < pandemic> right, but it should give them an error letting them know it's needed
20:35:31 @chilts and I'd rather throw right there if they _don't_ supply keys

20:35:34 < pandemic> I think AWS returns that
20:35:56 @chilts true, but then that requires a round-trip and it's better to die earlier than later
20:36:08 @chilts ie. it'll die (usually) on program startup if you don't supply a key
20:36:15 < pandemic> yeah
20:36:21 @chilts not sure which is best yet
20:36:23 @chilts :)
20:36:26 @chilts but I like both ideas
20:36:38 < pandemic> well, you could check if both are absent, if they are both absent then allow it
20:36:46 < pandemic> if only one is present, immediately failt
20:36:57 < pandemic> if both are present, then pass it along and sign it
20:37:33 @chilts ok, litmus test, in what case would you be running the _same_ code and you may or may not have the keys?
20:37:33 < pandemic> AWS either requires both or none i believe
20:38:09 @chilts I suspect that'll never happen, so the reality is it's two different bits of code ... so in each case you call either .Sqs or .SqsUnsigned
20:38:20 @chilts I'd rather have that API than something ambisuous
20:38:27 @chilts ambiguous
20:38:49 < pandemic> well, i was thinking that it may be simpler to update the amazon.js file so that this works globally rather than building a separate module for each unsigned version
20:39:17 < pandemic> IF there are other AWS services that allow you to call them without passing the keys
20:39:31 < pandemic> I'm not sure which services (if any other than SQS) allow that
20:39:38 @chilts I don't there are to be honest
20:39:47 < pandemic> haha, yeah
20:39:56 @chilts and I'd rather do one bit of work once now, than reply to lots of bug requests since they didn't provide the keys :)
20:39:58 < pandemic> well, honestly, either way works for me :)
20:40:04 < pandemic> lol
20:40:06 @chilts ok cool ... thanks for thrashing it out
20:40:08 < pandemic> yeah, i understand
20:40:15 < pandemic> haha no problem :)
20:40:17 @chilts I'll paste into the issue now :)

**Comment by stormic-nomad-nishant** [comment]
hey Michael,

Could you help me out and let me know how are you able to access the SQS queue without any credentials ? The way i see it i am using boto.sqs.connect_to_region() which requires the credentials to be passed .

Regards

**Comment by chilts** [comment]
AwsSum is now deprecated in favour of the offical aws-sdk from Amazon. Thanks for opening this originally.
