### ISSUE TITLE
Inconsistency in how awsAccountId must be specified

### ISSUE THREAD

**Issue by dmcbeath** [chilts/awssum#83]
I noticed an anomaly with the Amazon SQS client.

When I use the DynamoDB client, I do something like this

 var ddb = new DynamoDB({
    'accessKeyId' : 'myaccesskey',
    'secretAccessKey' : mysecretkey',
    'awsAccountId' : '1111-2222-3333',
    'region' : amazon.US_EAST_1
 });

 and, everything works fine.  However, this similar approach doesn't work for
 the SQS client.

 var sqs = new Sqs({
    'accessKeyId' : 'myaccesskey',
    'secretAccessKey' : mysecretkey',
    'awsAccountId' : '1111-2222-3333',
    'region' : amazon.US_EAST_1
 });

 Instead, I need to remove the hyphens from the awsAccountId.

 var sqs = new Sqs({
    'accessKeyId' : 'myaccesskey',
    'secretAccessKey' : mysecretkey',
    'awsAccountId' : '111122223333',
    'region' : amazon.US_EAST_1
 });

 Otherwise, I get an error indicating the address is not a valid sqs
 endpoint.  Not a big deal, just seems a bit inconsistent.

**Comment by chilts** [comment]
Hi Darin,

For the 2nd part of your issue in SQS, I have now changed the amazon.js file to be able to accept your awsAccountId() as either '111122223333' or '1111-2222-3333'. Internally, this is kept as two separate values and the appropriate one used in the correct places ... so in the case of SQS it uses the version _without_ the underscores! :)

I think that should fix your 2nd issue.

For your first issue, Amazon DynamoDB no longer requires AwsAccountId since it is now using Signature v4 rather than the STS service. So we didn't fix this, but just circumvented it in a good way.

Hope that helps.

Cheers,
Andy

**Comment by dmcbeath** [comment]
Thank you.  I do have another question.  Do you have the ability to generated signed URLs for content in S3 using awssum?  I'm looking around in the examples and haven't noticed anything yet.

Thanks.

Darin.

**Comment by chilts** [comment]
Hi Darin,

No, not yet. Could you open an issue for me and I can take a look in the next week or so. :)

Cheers,
Andy
