### ISSUE TITLE
CloudFront - GetDistributionConfig without etag

### ISSUE THREAD

**Issue by karlvlam** [chilts/awssum#89]
CloudFront.PutDistributionConfig() needs an "If-Match" option which is the "etag" header of GetDistributionConfig(), which is not  passed to the callback function. Could it be passed ?

**Comment by chilts** [comment]
Hiya,

Thanks for reporting this. I've fixed it for:
- PutDistributionConfig
- DeleteDistribution
- PutStreamingDistributionConfig
- DeleteStreamingDistribution
- DeleteOriginAccessIdentity

I had the param there, but it would have been passed in a header as 'IfMatch' rather than 'If-Match'. :) Sorry about that.

Can you try master and let me know if it's all okay for you. Otherwise, I'll be doing a release to npm in a week or so if you can wait.

Cheers,
Andy

**Comment by karlvlam** [comment]
Hi Andy,

Please correct me if I am wrong.

There should be an "etag" header return from GetDistributionConfig(), which is used to update the config when use PutDistributionConfig(). I can see the "etag" of GetDistributionConfig() in debug mode, but the value is not passed to the callback so I cannot get and use it on  PutDistributionConfig().

Thank you.
Karl
