### ISSUE TITLE
S3 has the wrong parameters

### ISSUE THREAD

**Issue by KalAvroniev** [chilts/awssum#95]
Hey guys,
First off great job on porting AWS to node.
I've been using AWS PHP SDK for quite sometime and recently started using your node module, mainly the S3 and SES.

I'm finding some differences between your code and AWS api documentation.
As an example GetObjectMetadata parameters are actually headers, not only Range.
Also the same headers can be used for GetObject but you do not have them there at all.

I haven't had a look at the rest of the services but can you please add a quick fix for S3 at least. 
I'll update if I find any other issues with other services as I start using them.

Thanks,
Kal

**Comment by chilts** [comment]
Hi Kal,

Thanks for your report! Dang, I never noticed I'd put them as 'param' rather than header. Also, I've added all of those extra 4 headers to GetObject (it already had Range).

I've pushed this to GitHub so if you want it now can you use a git checkout of the repo and they'll be released in the next version of AwsSum (v0.12). :)

Thanks again,
Andy

**Comment by KalAvroniev** [comment]
Thanks
That was quick!

**Comment by KalAvroniev** [comment]
When is it going to be available via npm?

**Comment by chilts** [comment]
Not sure yet. Sorry. Will try and let you know when it does get released.
